ex5_js-functions
amerancee/external-courses pull request #4
Opened 2020-03-14 13:28 UTC by amerancee

2020-03-20 17:46 UTC, dfolomkin requested changes

2020-03-20 17:46 UTC, dfolomkin commented on src/ex5_js-functions/task.js
> +      Calculator.state += value;
1. Для этого существует специальное ключевое слово **this**. Сейчас ваш калькулятор работает. Но если мы захотим создать новый калькулятор через присвоение `const newCalculator = Calculator`, то его методы продолжат работать с состоянием старого Calculator. Вряд ли мы этого хотим.

2020-03-20 17:46 UTC, dfolomkin commented on src/ex5_js-functions/task.js
> +const Calculator = {
2. Имена объектов пишутся, начиная с маленькой буквы (camelCase). А с большой (PascalCase) - имена Конструкторов, которые по сути являются функциями. Функция-конструктор здесь более уместна, и с учетом замечания 1 позволит без проблем создавать новые экземляры калькулятора.

2020-03-21 14:12 UTC, amerancee commented on src/ex5_js-functions/task.js
> +      Calculator.state += value;
Мы пока не изучали ключевое слово **this** и функции-конструкторы. В задании также не было указания использовать это.

2020-03-21 14:14 UTC, amerancee commented on src/ex5_js-functions/task.js
> +const Calculator = {
Мы пока не изучали функции-конструкторы.
По поводу имени с большой буквы (Calculator) - именно так было указано в задании:
![image](https://user-images.githubusercontent.com/53399565/77228307-78414a80-6b97-11ea-82df-6442273cd187.png)

2020-03-23 08:02 UTC, dfolomkin commented on src/ex5_js-functions/task.js
> +const Calculator = {
В таком случае используйте функцию (обычную, не конструктор, но с большой буквы, как требует задание), которая возвращает объект с методами, и замыкание. Замыкание позволит избежать проблемы из замечания 1.

2020-03-23 20:17 UTC, aneelia commented on src/ex5_js-functions/task.js
> +const Calculator = {
думаю этот вариант подойдет, с оглядкой на изученные материалы. стоит переформулировать задание, чтобы не было разногласий в дальнейшем<br>
 @amerancee  если хочешь, можешь для себя калькулятор переписать потом, когда изучим this

2020-03-23 20:17 UTC, merged