ex6_js-array-methods
amerancee/external-courses pull request #5
Opened 2020-03-21 14:08 UTC by amerancee

2020-03-23 11:16 UTC, dfolomkin requested changes

2020-03-23 11:16 UTC, dfolomkin commented on src/ex6_js-array-methods/task-03.js
> +		if (callback(array[i], i, array) === false) {
callback уже возвращает булево значние, остается только инвертировать

2020-03-23 14:51 UTC, amerancee commented on src/ex6_js-array-methods/task-03.js
> +		if (callback(array[i], i, array) === false) {
Исправил строку '4': if (!callback) ...

2020-03-24 07:49 UTC, dfolomkin approved these changes
ready to merge

2020-04-10 14:05 UTC, merged